title = "benchmarking parameters"

[debug]
time_limit = 20 # seconds
threads = 1
number_replicates = 1
solvers = ["add_gurobi_solver", "add_cbc_solver"]

[main]
time_limit = 1e+3 # seconds
threads = 1
number_replicates = 5
solvers = ["add_gurobi_solver", "add_rsymphony_solver", "add_cplex_solver", "add_cbc_solver"]
