title = "benchmarking parameters"

[debug]
## parameters
solver = ["add_gurobi_solver", "add_rsymphony_solver"]
objective = ["add_min_set_objective", "add_min_shortfall_objective"]
boundary_penalty_value = [0.0, 0.001, 0.01]
relative_target = [0.1, 0.15, 0.2]
number_replicates = 2
budget = [0.1] # budget for budget-limited objectives (0.1 = 10% of total cost)
## solver arguments
time_limit = 20 # seconds
threads = 1
gap = [0.1]

[release]
## parameters
number_replicates = 1
relative_target = [0.1, 0.15, 0.2, 0.3]
boundary_penalty_value = [0.0, 0.001, 0.01]
budget = [0.1] # budget for budget-limited objectives (0.1 = 10% of total cost)
solver = ["add_gurobi_solver", "add_rsymphony_solver", "add_cplex_solver", "add_cbc_solver", "add_lpsymphony_solver"]
objective = ["add_min_set_objective", "add_min_shortfall_objective"]
## solver arguments
time_limit = 1e+9 # seconds
threads = 1
gap = [0.05]
