title = "general parameters"

[debug]
threads = 1
raster_maxmemory = 1.0e+11 #100GB
raster_chunksize =1.0e+10 #10GB

[release]
threads = 20
raster_maxmemory = 1.0e+11 #100GB
raster_chunksize =1.0e+10 #10GB
