title = "general parameters"

[debug]
threads = 2
raster_maxmemory = 5.0e+9 # default
raster_chunksize = 1.0e+8 # default

[release]
threads = 1
raster_maxmemory = 1.0e+11 #100GB
raster_chunksize =1.0e+10 #10GB
